apiVersion: v1
kind: Secret
metadata:
  name: model-serving-secrets
  namespace: ai-models
type: Opaque
stringData:
  # Database connection (will be populated from AWS Secrets Manager)
  DATABASE_URL: "postgresql://username:password@host:5432/dbname"
  
  # Redis connection (will be populated from AWS Secrets Manager)
  REDIS_URL: "redis://:auth_token@host:6379"
  
  # S3 configuration
  AWS_S3_BUCKET: "model-artifacts-bucket"
  
  # Model serving API keys
  MODEL_API_KEY: "your-model-api-key-here"
  
  # Monitoring and observability
  PROMETHEUS_TOKEN: "your-prometheus-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: ai-models
type: kubernetes.io/dockerconfigjson
data:
  # Docker registry credentials for pulling model images
  # This should be populated with actual ECR credentials
  .dockerconfigjson: eyJhdXRocyI6e319

