apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bert-ner-model-hpa
  namespace: ai-models
spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: resnet-classifier-model-hpa
  namespace: ai-models
spec:
  minReplicas: 0
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90

